apiVersion: apps/v1
kind: Deployment
metadata:
  name: killer
  namespace: default
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nope
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nope
    spec:
      containers:
      - name: moeter
        image: zepp/fintest:43
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "3"
            memory: "3Gi"