- name: Ensure all k8s related groups are created
  when: worker is defined
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
  with_items: "{{ k8s_groups }}"
  tags: [k8s-worker]

- name: Ensure all k8s related users are created and added to the requiered groups
  when: worker is defined
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.groups }}"
    groups: "{{ item.groups }}"
  with_items: "{{ k8s_users }}"
  tags: [k8s-worker]

- name: Ensure all needed directories are present
  when: worker is defined
  file:
    state: directory
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ directories }}"
  tags: [k8s-worker]

- name: Ensure all needed binarys are present
  when: worker is defined
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ binarys }}"
  tags: [k8s-worker]

- name: Ensure all needed configs are present
  when: worker is defined
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ configs }}"
  tags: [k8s-worker]

- name: Ensure all k8s related certificates are present
  when: worker is defined
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ certs }}"
  tags: [k8s-worker]

- name: Ensure all needed systemd unitfiles are present
  when: worker is defined
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ systemd_units }}"
  tags: [k8s-worker]

- name: Ensure all needed service-configs are present
  when: worker is defined
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ service_configs }}"
  tags: [k8s-worker]

- name: Ensure services have restarted
  when: worker is defined
  systemd:
    state: restarted
    name: "{{ item.name }}"
    enabled: True
    daemon_reload: yes
  with_items: "{{ services }}"
  tags: [k8s-worker]